### ISSUE TITLE
preprocess.py -config - not working.

### ISSUE THREAD

**Issue by markus93** [mt2017-tartu-shared-task/nmt-system-B#1]
I am not able to get parameter -config working for script preprocess.py
I have tried different formats for config file:
1.  -train_src bpe.cleaned-tc-tok-train.et
2. train_src = bpe.cleaned-tc-tok-train.et
3. --train_src bpe.cleaned-tc-tok-train.et

Every hyperparameter is on separate row, however I still get error that: "preprocess.py: error: argument -train_src is required"

**Comment by MaksymDel** [comment]
Nice point! 

Usually, it is a good practice to specify config files with options separately. Some frameworks even allow specifying parameters through the command line and add -save_config option to save these options to file post factum. 

However, config functionality is broken in OpenNMT-py now. Presence of the broken feature or absence of some obvious feature is every-day problem researchers meet while using open-source tools. 

So, teams, please specify parameters as command line arguments (like we were doing during the lab), and save the whole command with arguments you run as .txt (or .sh) file. This way we (and you) still can keep it reproducible. 

However, since you have to use SLURM, you will have these files for free (just commit .sh SLURM files).

@mt2017-tartu-shared-task/imperium 
@mt2017-tartu-shared-task/mali 
@mt2017-tartu-shared-task/powerrangers 
@mt2017-tartu-shared-task/quidditchchampions 
@mt2017-tartu-shared-task/researchers 
@mt2017-tartu-shared-task/toneko 
@fishel @maxdel
