### ISSUE TITLE
Preprocess.py - list index out of range

### ISSUE THREAD

**Issue by markus93** [mt2017-tartu-shared-task/nmt-system-B#2]
Given error was thrown when running preprocess.py script - [error .txt](https://github.com/mt2017-tartu-shared-task/nmt-system-B/files/1339887/error.txt)

**Comment by MaksymDel** [comment]
Please, add full script you run

**Comment by markus93** [comment]
Code - [7-preprocess.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-B/files/1340259/7-preprocess.txt)

**Comment by MaksymDel** [comment]
Since we shuffle data randomly, we can get unlucky dev set (e.g. with empty lines). The dev set is fed to the OpenNMT-py preprocess.py script so it can serialize it (create .pt file), and it wants it to be cleaned.

So clean the dev set beforehand (i.e. execute clean-corpus.perl with dev set (e.g. bpe.*dev) as an argument).

@mt2017-tartu-shared-task/imperium 
@mt2017-tartu-shared-task/mali 
@mt2017-tartu-shared-task/powerrangers 
@mt2017-tartu-shared-task/quidditchchampions 
@mt2017-tartu-shared-task/researchers 
@mt2017-tartu-shared-task/toneko 
@fishel @maxdel

Note, that cleaning the dev set is specific to openNMT, not needed for test set, and not needed for most other frameworks

**Comment by MaksymDel** [comment]
Hi Markus,

did it help with your problem?

**Comment by markus93** [comment]
Hey, it seemed to help with given problem. 

However at the moment, I get following error"slurmstepd: error: Exceeded step memory limit at some point, slurmstepd: error: Exceeded job memory limit at some point". For that I used 50GB of RAM.

Next tried on 56Gb (could not allocate more), it have ran over 24 hours. So it seems that something is still buggy.

**Comment by MaksymDel** [comment]
24 hours is too much. Try vocabulary size of ~30.000.

**Comment by markus93** [comment]
Tried smaller vocabulary size (30k), however same problem occured. So I used GPU machine in order to allocate more RAM (150GB), which was sufficient.
